import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { CREDIT_PACKS, PRICING } from '../../data/landing-content';
import { ChapterHead } from './ChapterHead';
export function PricingSection() {
    return (_jsxs(_Fragment, { children: [_jsx(ChapterHead, { label: "Chapter III \u00B7 \uAC00\uACA9", heading: "\uC4F4 \uB9CC\uD07C\uB9CC.", id: "pricing" }), _jsxs("section", { className: "chapter", children: [_jsx("div", { className: "pricing-grid", children: PRICING.map((p) => (_jsxs("div", { className: `price-cell${p.featured ? ' featured' : ''}`, children: [_jsx("div", { className: "price-name sans", children: p.name }), _jsx("div", { className: "price-num sans", children: p.price }), _jsxs("div", { className: "price-period sans", children: [p.period ? `${p.period} · ` : '', p.sub] }), _jsx("a", { href: "#", className: `price-cta ${p.ctaVariant} sans`, children: p.cta }), _jsx("ul", { className: "price-list", children: p.features.map((f) => {
                                        const isSub = f.startsWith('└');
                                        return (_jsx("li", { className: isSub ? 'price-list-sub' : '', children: isSub ? f.replace(/^└\s*/, '') : f }, f));
                                    }) })] }, p.name))) }), _jsxs("div", { className: "credit-section", children: [_jsx("p", { className: "credit-section-label sans", children: "\uAD6C\uB3C5 \uC5C6\uC774 \uD55C \uBC88\uB9CC \uCDA9\uC804\uD558\uACE0 \uC2F6\uB2E4\uBA74" }), _jsx("div", { className: "credit-grid", children: CREDIT_PACKS.map((pack) => (_jsxs("a", { href: "#", className: "credit-card", "aria-label": `${pack.price} 크레딧 구매하기`, children: [_jsx("div", { className: "credit-price sans", children: pack.price }), _jsx("div", { className: "credit-amount sans", children: pack.credit }), _jsx("div", { className: "credit-bonus sans", children: pack.bonus }), _jsx("span", { className: "credit-card-cta sans", children: "\uAD6C\uB9E4\uD558\uAE30 \u2192" })] }, pack.price))) })] })] })] }));
}
