upstream backend {
    server spring-boot-blue:8080;
}

upstream ai {
    server fastapi-blue:8000;
}

upstream frontend {
    server react-web-blue:80;
}

upstream landing {
    server landing-blue:80;
}
