upstream backend {
    server spring-boot-green:8080;
}

upstream ai {
    server fastapi-green:8000;
}

upstream frontend {
    server react-web-green:80;
}

upstream landing {
    server landing-green:80;
}
